# Generated by Django 3.2.5 on 2022-04-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phoneNumber',
        ),
    ]
