# Generated by Django 3.2.5 on 2022-04-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesystem', '0002_auto_20220401_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='directorID',
            field=models.ForeignKey(default=11111, on_delete=django.db.models.deletion.PROTECT, related_name='movie_directors', to='moviesystem.director'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='watch',
            field=models.ManyToManyField(to='moviesystem.Movie'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('reviewedMovie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_movies', to='moviesystem.movie')),
                ('writtenby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_users', to='moviesystem.user')),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=255)),
                ('actorID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='act_actors', to='moviesystem.actor')),
                ('directorID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='act_directors', to='moviesystem.director')),
            ],
        ),
    ]
