# Generated by Django 3.2.5 on 2022-04-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesystem', '0004_auto_20220401_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['ratingFromTomato']},
        ),
        migrations.RenameField(
            model_name='act',
            old_name='actorID',
            new_name='actor_name',
        ),
        migrations.RenameField(
            model_name='act',
            old_name='directorID',
            new_name='director_name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='directorID',
            new_name='director_name',
        ),
    ]
