# Generated by Django 3.2.5 on 2022-04-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesystem', '0006_alter_movie_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='Movie',
        ),
    ]
