# Generated by Django 3.2.5 on 2022-04-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesystem', '0007_alter_movie_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='director',
            table='Director',
        ),
    ]
