# Generated by Django 3.2.5 on 2022-04-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesystem', '0008_alter_director_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='act',
            table='Act',
        ),
        migrations.AlterModelTable(
            name='actor',
            table='Actor',
        ),
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
