# Generated by Django 3.2.5 on 2022-04-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesystem', '0009_auto_20220401_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewedMovie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='writtenby',
        ),
        migrations.AddField(
            model_name='review',
            name='moviename',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='moviesystem.movie'),
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='moviesystem.user'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='moviesystem.director'),
        ),
    ]
