# Generated by Django 3.2.5 on 2022-04-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesystem', '0010_auto_20220401_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='actor_name',
            new_name='actorID',
        ),
        migrations.RenameField(
            model_name='act',
            old_name='director_name',
            new_name='directorID',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director_name',
            new_name='directorID',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='moviename',
            new_name='movieID',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='userID',
        ),
    ]
